// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TradeSpaceApi.data;

#nullable disable

namespace TradeSpaceApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TradeSpaceApi.models.CountryModel", b =>
                {
                    b.Property<string>("Country")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Adjustment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryGroup")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FirstValueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HistoricalDataSymbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("LatestValue")
                        .HasColumnType("float");

                    b.Property<DateTime>("LatestValueDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("PreviousValue")
                        .HasColumnType("float");

                    b.Property<DateTime>("PreviousValueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Country");

                    b.ToTable("CountriesData");

                    b.HasData(
                        new
                        {
                            Country = "Mexico",
                            Adjustment = "NSA",
                            Category = "Employment Rate",
                            CategoryGroup = "Labour",
                            CreateDate = new DateTime(2015, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstValueDate = new DateTime(2005, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Frequency = "Monthly",
                            HistoricalDataSymbol = "MEXICOEMPRAT",
                            LatestValue = 97.120000000000005,
                            LatestValueDate = new DateTime(2023, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PreviousValue = 97.040000000000006,
                            PreviousValueDate = new DateTime(2023, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Source = "Instituto Nacional de Estadística y Geografía (INEGI)",
                            SourceURL = "https://www.inegi.org.mx/",
                            Title = "Mexico Employment Rate",
                            URL = "/mexico/employment-rate",
                            Unit = "percent"
                        },
                        new
                        {
                            Country = "Nigeria",
                            Adjustment = "NSA",
                            Category = "Employment Rate",
                            CategoryGroup = "Labour",
                            CreateDate = new DateTime(2015, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstValueDate = new DateTime(2015, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Frequency = "Monthly",
                            HistoricalDataSymbol = "NGN",
                            LatestValue = 76.700000000000003,
                            LatestValueDate = new DateTime(2023, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PreviousValue = 73.599999999999994,
                            PreviousValueDate = new DateTime(2023, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Source = "Central Bank of Nigeria",
                            SourceURL = "https://www.cbn./blahblah/",
                            Title = "Nigeria Employment Rate",
                            URL = "/nigeria/employment-rate",
                            Unit = "percent"
                        },
                        new
                        {
                            Country = "United States",
                            Adjustment = "NSA",
                            Category = "Employment Rate",
                            CategoryGroup = "Labour",
                            CreateDate = new DateTime(2015, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstValueDate = new DateTime(2005, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Frequency = "Monthly",
                            HistoricalDataSymbol = "United-StatesUSD",
                            LatestValue = 60.200000000000003,
                            LatestValueDate = new DateTime(2023, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PreviousValue = 60.399999999999999,
                            PreviousValueDate = new DateTime(2023, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Source = "World Bank",
                            SourceURL = "https://www.worldbank.org/",
                            Title = "United States Employment Rate",
                            URL = "/United-States/employment-rate",
                            Unit = "percent"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
